class UsersExceptions(Exception):
    pass


class UserAlreadyExistsException(UsersExceptions):
    pass
